### PR TITLE
Added overview to Basic OOP in README.md

### PR DESCRIPTION
**Pull request by kishore-narendran**
- All the curriculum for OOP has been added as a table in the README.md.

### CODE REVIEW

**Comment by sigit-prayoga** [comment]
All good. @mhaidarh: However we need to finish 'TBA' part

**Comment by mhaidarhanif** [comment]
@kishore-narendran Thank you again for migrating them.
@sigit-prayoga Definitely, we probably can do that in Sunday or next week.

**Comment by mhaidarhanif** [comment]
Almost forgot. Should we omit the Duration?

**Comment by mhaidarhanif** [comment]
Okay, we should omit them. I actually planned to edit them tonight, but I should have a rest right now.

**Pull request merged**
