### PR TITLE
Refactored file names

### PR DESCRIPTION
**Pull request by kishore-narendran**

### CODE REVIEW

**Comment by kishore-narendran** [comment]
This should solve the possible confusion that can arise from the file names.

**Comment by mhaidarhanif** [comment]
Thank you, I missed the source code file name in the document.

**Comment by mhaidarhanif** [comment]
Wait, should it be `BasicJavaProgramming.java` or `BasicsOfProgramming.java` or `BasicsOfJavaProgramming.java`?

cc: @sigit-prayoga

**Comment by kishore-narendran** [comment]
`BasicJavaProgramming.java` seems better to me.

**Pull request merged**
